name: WordPress Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |-
            extends: default
            rules:
              document-start:
                present: false
              truthy:
                check-keys: false
            ignore:
              - node_modules
              - vendor

  php-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: overtrue/phplint@9.1.2

  js-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: npm
      - run: npm ci --include=dev
      - run: npm run lint:js

  wordpress-phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        id: test
        uses: holyhope/test-wordpress-plugin-github-action@v2.0.2
        with:
          plugin_slug: uagb-static-form
      - uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: ${{ steps.test.outputs.junit_report }}

  language-files-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: holyhope/test-wordpress-languages-github-action@v4.0.0
        id: languages
        with:
          slug: uagb-static-form
          exclude: |-
            .github
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: language-patch
          path: ${{ steps.languages.outputs.patch_path }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: npm
      - run: npm ci --include=dev
      - run: npm run build
      - run: npm run plugin-zip
      - uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: '@natbienetre/uagb-static-form.zip'
